sudo: required
language: c++
install:
before_script:
  - sudo apt-get install python
  - git clone https://github.com/CxxTest/cxxtest
  - ./cxxtest/bin/cxxtestgen –error-print --runner=ErrorPrinter -o runner.cc test/test1.h
script:
  - mkdir build && cd build && cmake .. && make && make test
notifications:
  email:
    - kam.cpp@gmail.com
